version: '3'

services:
#  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:latest'
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bed_brkfst
    volumes:
      - ~/db-data/postgres/:/var/lib/postgresql/data/

 #  run with: "docker compose up -d"
